In [1]:
import pandas as pd
import numpy as np


from sklearn.preprocessing import Binarizer, binarize

In [23]:
num_list = [[ -1000, 0],
            [  500, -3000],
            [  100, 650]]

In [24]:
binarizer = Binarizer()
binarizer

Binarizer(copy=True, threshold=0.0)

In [25]:
binarizer.fit(num_list)

Binarizer(copy=True, threshold=0.0)

In [26]:
binarized_list = binarizer.transform(num_list)

binarized_list

array([[0, 0],
       [1, 0],
       [1, 1]])

In [27]:
binarizer = Binarizer(threshold=500)

binarizer.fit_transform(num_list)

array([[0, 0],
       [0, 0],
       [0, 1]])

In [35]:
binarizer = Binarizer(threshold=[0, 100])

binarizer.fit_transform(num_list)

array([[0, 0],
       [1, 0],
       [1, 1]])

### Using the binarizer to make numeric values categorical

In [66]:
diet_data = pd.read_csv('Datasets/diet_data.csv')

In [68]:
diet_data.head()

Date  Stone  Pounds  Ounces  weight_oz  calories cals_per_oz  \
0  7/30/2018   12.0     2.0     6.0     2726.0    1950.0        0.72   
1  7/31/2018   12.0     0.0     8.0     2696.0    2600.0        0.96   
2   08/01/18   12.0     1.0     0.0     2704.0    2500.0        0.92   
3   08/02/18   12.0     1.0     0.0     2704.0    1850.0        0.68   
4   08/03/18   11.0    12.0     8.0     2664.0    2900.0        1.09   

   five_donuts  walk  run  wine  prot  weight  change  
0          1.0   1.0  0.0   0.0   0.0     0.0   -30.0  
1          1.0   0.0  0.0   0.0   0.0     0.0     8.0  
2          1.0   1.0  0.0   0.0   0.0     0.0     0.0  
3          1.0   1.0  0.0   1.0   0.0     0.0   -40.0  
4          1.0   1.0  0.0   0.0   0.0     0.0    14.0

In [69]:
diet_data = diet_data.dropna()

diet_data = diet_data.drop(['Date', 'Stone', 'Pounds', 'Ounces'], axis=1)

In [70]:
diet_data = diet_data.astype(np.float64)

In [71]:
diet_data.head()

weight_oz  calories  cals_per_oz  five_donuts  walk  run  wine  prot  \
0     2726.0    1950.0         0.72          1.0   1.0  0.0   0.0   0.0   
1     2696.0    2600.0         0.96          1.0   0.0  0.0   0.0   0.0   
2     2704.0    2500.0         0.92          1.0   1.0  0.0   0.0   0.0   
3     2704.0    1850.0         0.68          1.0   1.0  0.0   1.0   0.0   
4     2664.0    2900.0         1.09          1.0   1.0  0.0   0.0   0.0   

   weight  change  
0     0.0   -30.0  
1     0.0     8.0  
2     0.0     0.0  
3     0.0   -40.0  
4     0.0    14.0

In [72]:
diet_data.describe()

weight_oz     calories  cals_per_oz  five_donuts        walk  \
count   140.000000   140.000000   140.000000   140.000000  140.000000   
mean   2687.700000  3180.714286     1.183643     0.371429    0.678571   
std      28.663189  1478.753433     0.551700     0.484922    0.468702   
min    2628.000000  1400.000000     0.510000     0.000000    0.000000   
25%    2670.000000  2187.500000     0.807500     0.000000    0.000000   
50%    2689.000000  2575.000000     0.955000     0.000000    1.000000   
75%    2704.000000  3850.000000     1.450000     1.000000    1.000000   
max    2768.000000  9150.000000     3.450000     1.000000    1.000000   

              run        wine        prot      weight      change  
count  140.000000  140.000000  140.000000  140.000000  140.000000  
mean     0.250000    0.307143    0.178571    0.442857   -1.485714  
std      0.434568    0.462966    0.384368    0.498508   25.098793  
min      0.000000    0.000000    0.000000    0.000000  -58.000000  
25%      0.000000    0.000000    0.000000    0.000000  -18.000000  
50%      0.000000    0.000000    0.000000    0.000000   -3.000000  
75%      0.250000    1.000000    0.000000    1.000000   16.000000  
max      1.000000    1.000000    1.000000    1.000000  102.000000

In [73]:
median_calories = diet_data['calories'].median()

median_calories

2575.0

In [74]:
binarizer = Binarizer(threshold=median_calories)

diet_data['calories_above_median'] = binarizer.fit_transform(diet_data[['calories']])

In [75]:
diet_data.head()

weight_oz  calories  cals_per_oz  five_donuts  walk  run  wine  prot  \
0     2726.0    1950.0         0.72          1.0   1.0  0.0   0.0   0.0   
1     2696.0    2600.0         0.96          1.0   0.0  0.0   0.0   0.0   
2     2704.0    2500.0         0.92          1.0   1.0  0.0   0.0   0.0   
3     2704.0    1850.0         0.68          1.0   1.0  0.0   1.0   0.0   
4     2664.0    2900.0         1.09          1.0   1.0  0.0   0.0   0.0   

   weight  change  above_median  
0     0.0   -30.0           0.0  
1     0.0     8.0           1.0  
2     0.0     0.0           0.0  
3     0.0   -40.0           0.0  
4     0.0    14.0           1.0

In [76]:
mean_calories_per_oz = diet_data['cals_per_oz'].mean()

mean_calories_per_oz

1.1836428571428572

In [80]:
diet_data['cals_per_oz_above_mean'] = binarize(diet_data[['cals_per_oz']], 
                                               threshold=mean_calories_per_oz)

In [81]:
diet_data.sample(10)

weight_oz  calories  cals_per_oz  five_donuts  walk  run  wine  prot  \
21      2710.0    2000.0         0.74          0.0   1.0  0.0   0.0   0.0   
41      2692.0    5200.0         1.93          0.0   1.0  1.0   1.0   1.0   
126     2724.0    2500.0         0.92          1.0   1.0  1.0   0.0   0.0   
71      2688.0    1400.0         0.52          0.0   1.0  0.0   0.0   0.0   
76      2696.0    6450.0         2.39          0.0   0.0  1.0   0.0   0.0   
15      2662.0    2400.0         0.90          1.0   1.0  0.0   0.0   0.0   
94      2664.0    5400.0         2.03          0.0   1.0  0.0   1.0   0.0   
37      2672.0    2500.0         0.94          0.0   1.0  1.0   0.0   1.0   
67      2744.0    2900.0         1.06          1.0   1.0  0.0   1.0   0.0   
0       2726.0    1950.0         0.72          1.0   1.0  0.0   0.0   0.0   

     weight  change  above_median  cals_per_oz_above_mean  
21      0.0   -18.0           0.0                     0.0  
41      1.0   -12.0           1.0                     1.0  
126     1.0   -34.0           0.0                     0.0  
71      0.0   -24.0           0.0                     0.0  
76      1.0    40.0           1.0                     1.0  
15      0.0    -4.0           0.0                     0.0  
94      0.0    44.0           1.0                     1.0  
37      1.0   -16.0           0.0                     0.0  
67      0.0    -2.0           1.0                     0.0  
0       0.0   -30.0           0.0                     0.0