## Function Transformer

In [24]:
import numpy as np
import pandas as pd

import math

from sklearn.preprocessing import FunctionTransformer

In [18]:
arr = np.array([[0, -1], 
                [-6, 7]])
arr

array([[ 0, -1],
       [-6,  7]])

In [23]:
abs_transformer = FunctionTransformer(np.abs, validate=False)

abs_transformer.transform(arr)

array([[0, 1],
       [6, 7]])

In [25]:
def calculate_squares(x):
    return x * x

In [28]:
squares_transformer = FunctionTransformer(calculate_squares, validate=False)

squares_arr = squares_transformer.transform(arr)

squares_arr

array([[ 0,  1],
       [36, 49]])

In [29]:
inverse_transformer = FunctionTransformer(inverse_func=np.sqrt, validate=False)

inverse_transformer

FunctionTransformer(accept_sparse=False, check_inverse=True, func=None,
          inv_kw_args=None, inverse_func=<ufunc 'sqrt'>, kw_args=None,
          pass_y='deprecated', validate=False)

In [30]:
orig_arr = inverse_transformer.inverse_transform(squares_arr)

orig_arr

array([[0., 1.],
       [6., 7.]])