## Creating Numpy Arrays



In [ ]:
!pip install numpy --upgrade

In [1]:
import numpy as np

#### 1. Create an array from a regular Python list or tuple using the array function

In [21]:
array_one = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [5]:
numbers = [9,8,7,6]
array_two = np.array(numbers)
array_two

array([9, 8, 7, 6])


#### 2. NumPy offers several functions to create arrays with initial placeholder content
Create an array of zeros with desired shape (x,y)
* x == number of rows
* y == number of columns in array

In [7]:
array_of_zeroes = np.zeros((3,4))
array_of_zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
array_of_ones = np.ones((3,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

##### Use dtype in order to specify the data type

In [9]:
array_of_ones_int = np.ones((3,4),dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

#### np.empty() is not the same as np.zeros()
One may get the same output. But np.empty() returns a new array of given shape and type, without initializing entries (the entries may be zero but not always)
<br />
Used when you plan to populate the array but need to create one quickly first. If you want an array of zeros, use np.zeros()

In [10]:
array_empty = np.empty((2,3))  
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

#### np.eye() creates an eyedentity matrix

In [11]:
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 3. To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists

arange(start, stop, step, dtype)

In [9]:
array_of_evens = np.arange(2, 20, 2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

#### It also accepts float arguments

In [12]:
array_of_floats = np.arange( 0, 2, 0.3)
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

#### Two Dimensional Arrays

In [13]:
array_2d = np.array([(2,4,6),(3,5,7)]) 
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [14]:
array_2d.shape

(2, 3)

#### Using reshape to create n dimensional arrays

In [15]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [16]:
array_nd = np.arange(6).reshape(3,2) 
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

The reshape will only take arguments that multiply to the number in arange function.
For example:
for arange(8), the possible combinations for reshape are (2,4), (4,2), (2,2,2)

In [17]:
array_nd = np.arange(6).reshape(3,4) 
array_nd

ValueError: cannot reshape array of size 6 into shape (3,4)

In [18]:
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

<b>ones_like</b> : Produce an array of all 1’s with the given shape and dtype. ones_like takes another array and produces a ones array of the same shape and dtype. <br />
There's also a zeros_like and empty_like

In [24]:
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

### Array creation functions

<b>array</b> : Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype or explicitly specifying a dtype. Copies the input data by default.


<b>asarray</b> : Convert input to ndarray, but do not copy if the input is already an ndarray

<b>arange</b> : Like the built-in range but returns an ndarray instead of a list.

<b>ones, ones_like</b> : Produce an array of all 1’s with the given shape and dtype. ones_like takes another array and produces a ones array of the same shape and dtype.

<b>zeros, zeros_like</b> : Like ones and ones_like but producing arrays of 0’s instead

<b>empty, empty_like</b> : Create new arrays by allocating new memory, but do not populate with any values like ones and zeros

<b>eye, identity</b> : Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere)