## Fancy Indexing - Boolean Arrays

When we index arrays with arrays of (integer) indices we are providing the list of indices to pick. With boolean indices the approach is different; we explicitly choose which items in the array we want and which ones we don’t.

Frequently this type of indexing is used to select the elements of an array that satisfy some condition

In [1]:
import numpy as np

In [2]:
a = np.arange(16).reshape(4,4)

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Now we find the elements that are greater than 9. This will return a numpy array of the same shape as our original array. 

In [5]:
indx_bool = a > 9

In [6]:
indx_bool

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

We use this array to select elements in a corresponding to 'true' values in the boolean array.

In [7]:
a[indx_boo]

array([10, 11, 12, 13, 14, 15])

We can do all of the above in a single concise statement

In [8]:
print(a[a > 9])

[10 11 12 13 14 15]


### Counting 

#### How many values less than 6?

In [11]:
a < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [9]:
np.count_nonzero(a < 6)

6

In [13]:
np.sum(a < 6)

6

#### How many values less than 6 in each row?

In [14]:
np.sum(a < 6, axis=1)

array([4, 2, 0, 0])

#### Are there any values greater than 8?

In [15]:
np.any(a > 8)

True

#### Are all values less than 10?

In [16]:
np.all(a < 10)

False

#### Are all values less than 100?

In [17]:
np.all(a < 100)

True

#### Are all values in each row less than 9?

In [19]:
np.all(a < 9, axis=1)

array([ True,  True, False, False])