In [1]:
import numpy as np

## Arithmetic Operations

If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. We will see what broadcasting is in the upcoming lessons.

In [9]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [3]:
a + b

array([15, 15, 15])

In [4]:
a - b

array([5, 5, 5])

In [5]:
a * b

array([50, 50, 50])

In [6]:
a / b

array([2., 2., 2.])

In [7]:
a % 3  

array([1, 1, 1])

In [8]:
a < 35

array([ True,  True,  True])

In [9]:
a > 25

array([False, False, False])

In [10]:
a ** 2

array([100, 100, 100])

## dot function or method

In [5]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0], [3,4]] )

print('A:\n', A)
print('B:\n', B)

A:
 [[1 1]
 [0 1]]
B:
 [[2 0]
 [3 4]]


#### This gives element-wise multiplication

In [12]:
A * B

array([[2, 0],
       [0, 4]])

#### This gives the matrix multiplication

In [13]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [14]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

## Modifying an existing array rather than create a new one

In [10]:
a  *= 3
a

array([30, 30, 30])

In [11]:
b += a
b

array([35, 35, 35])

## Unary Operators

In [12]:
ages = np.array([12,15,18,20])

In [13]:
ages.sum()

65

In [14]:
ages.min()

12

In [15]:
ages.max()

20

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array

In [16]:
numbers = np.arange(12).reshape(3,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Row and column operations
In a 2D array axis #0 represents columns. Axis #1 refers to rows

#### Sum up each column

In [19]:
numbers.sum(axis=0) 

array([12, 15, 18, 21])

#### Sum up each row

In [20]:
numbers.sum(axis=1)

array([ 6, 22, 38])

#### Minimum of each row

In [21]:
numbers.min(axis=1) 

array([0, 4, 8])