## Automatic Reshaping

To change the dimensions of an array, you can omit one of the sizes which will then be deduced automatically

We omit one dimension, and mention -1. -1 means that the length in that dimension is inferred

In [1]:
import numpy as np

In [2]:
a = np.arange(30)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

##### -1 means "whatever is needed"

In [4]:
a.shape = 2,-1,3  

In [5]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [6]:
a.shape

(2, 5, 3)

In [13]:
a.shape = 2,3,-1

In [10]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [11]:
a.shape

(2, 3, 5)

#### Be careful as usual with the stated dimensions
If you're specifying 2 out of 3 dimensions, the product of the two dimensions must be a divisor of the total number of elements in the array